### ISSUE TITLE
US5 - As a new user, I would like a given issue format

### ISSUE THREAD

**Issue by tototto** [AY2021S1-TIC4001-3/tp#14]
... so that I can know a structured way of using the app.

**Comment by tototto** [comment]
@pigoliver 

I believe we can close this issue. This is because we are following the given user format as per our design: 
E.g. add t/cannot submit s/assigned sv/high dl/20Sep2020 o/Jack

Are you agreeable to this?

**Comment by HongJiancheng** [comment]
Agree, thanks.
